### ISSUE TITLE
fail to achieve the expected results

### ISSUE THREAD

**Issue by maomaocun** [Flo771994/charfctgen#1]
Hello author, have you uploaded all the codes? When I run your main script with your default parameters, I fail to achieve the expected results.
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/1306f6cf-e826-4be7-a0fd-4ef1d6cae93f">

**Comment by florianbrueck** [comment]
Hi, 
I've set the hyperparamters in this code such that it should run on every computer (cpu). The short answer is that you should set the batch sizes _batchsizes, s_size_approx_ and the number of iterations much higher. For example, in the corresponding paper [](https://arxiv.org/abs/2401.04778) I have set them to 6000. There you can find more infos on the hyperparameters that I used in my simulations.

P.S: There will be an update of the paper/code with new examples very soon (about 2 weeks from now).
